-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 20:53:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zfm1-zde_keryo_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zfm1-zde_keryo_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zfm1-zde_keryo_1` DEFAULT CHARACTER SET utf8 ;
USE `zfm1-zde_keryo_1` ;



-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_gestionnaire_gst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_gestionnaire_gst` (
  `gst_id` INT NOT NULL AUTO_INCREMENT,
  `gst_pers` VARCHAR(80) NULL,
  `gst_assoc_nom` VARCHAR(40) NULL,
  `gst_assoc_pres` VARCHAR(80) NULL,
  PRIMARY KEY (`gst_id`))
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Salle_sal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Salle_sal` (
  `sal_id` INT NOT NULL AUTO_INCREMENT,
  `sal_capacité` INT NULL,
  `sal_nom` VARCHAR(45) NULL,
  `sal_adresse` VARCHAR(100) NULL,
  `t_gestionnaire_gst_gst_id` INT NOT NULL,
  PRIMARY KEY (`sal_id`),
  INDEX `fk_t_Salle_t_gestionnaire_gst1_idx` (`t_gestionnaire_gst_gst_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Salle_t_gestionnaire_gst1`
    FOREIGN KEY (`t_gestionnaire_gst_gst_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_gestionnaire_gst` (`gst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Admin_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Admin_adm` (
  `adm_id` VARCHAR(20) NOT NULL,
  `adm_passord` VARCHAR(40) NULL,
  PRIMARY KEY (`adm_id`))
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Soiree_sor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Soiree_sor` (
  `sor_id` INT NOT NULL AUTO_INCREMENT,
  `sor_nom` VARCHAR(45) NULL,
  `sall_id` INT NOT NULL,
  PRIMARY KEY (`sor_id`),
  INDEX `fk_t_Soiree_sor_t_Salle1_idx` (`sall_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Soiree_sor_t_Salle1`
    FOREIGN KEY (`sall_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_Salle_sal` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Concert_con`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Concert_con` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_date_debut` DATETIME NULL,
  `con_date_fin` DATETIME NULL,
  `con-prix` DOUBLE NULL,
  `sor_id` INT NOT NULL,
  PRIMARY KEY (`con_id`),
  INDEX `fk_t_Concert_con_t_Soiree_sor1_idx` (`sor_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Concert_con_t_Soiree_sor1`
    FOREIGN KEY (`sor_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_Soiree_sor` (`sor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Billet_bil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Billet_bil` (
  `bil_id` INT NOT NULL AUTO_INCREMENT,
  `t_Concert_con_con_id` INT NOT NULL,
  PRIMARY KEY (`bil_id`),
  INDEX `fk_t_Billet_bil_t_Concert_con1_idx` (`t_Concert_con_con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Billet_bil_t_Concert_con1`
    FOREIGN KEY (`t_Concert_con_con_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_Concert_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_groupe_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_groupe_grp` (
  `grp_id` INT NOT NULL AUTO_INCREMENT,
  `grp_description` VARCHAR(100) NULL,
  `grp_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`grp_id`))
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Artiste_art`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Artiste_art` (
  `art_id` INT NOT NULL AUTO_INCREMENT,
  `art_nom` VARCHAR(40) NULL,
  `art_prenom` VARCHAR(40) NULL,
  `art_pseudo` VARCHAR(45) NULL,
  `art_ville` VARCHAR(45) NULL,
  `art_age` INT NULL,
  `grp_id` INT NOT NULL,
  PRIMARY KEY (`art_id`),
  INDEX `fk_t_Artiste_art_t_groupe_grp1_idx` (`grp_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Artiste_art_t_groupe_grp1`
    FOREIGN KEY (`grp_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_groupe_grp` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `zfm1-zde_keryo_1`.`t_Participe_par`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zfm1-zde_keryo_1`.`t_Participe_par` (
  `con_id` INT NOT NULL,
  `grp_id` INT NOT NULL,
  PRIMARY KEY (`con_id`, `grp_id`),
  INDEX `fk_t_Concert_con_has_t_groupe_grp_t_groupe_grp2_idx` (`grp_id` ASC) VISIBLE,
  INDEX `fk_t_Concert_con_has_t_groupe_grp_t_Concert_con2_idx` (`con_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_Concert_con_has_t_groupe_grp_t_Concert_con2`
    FOREIGN KEY (`con_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_Concert_con` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_Concert_con_has_t_groupe_grp_t_groupe_grp2`
    FOREIGN KEY (`grp_id`)
    REFERENCES `zfm1-zde_keryo_1`.`t_groupe_grp` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
